import json
import os
import tempfile
import numpy as np
import pytest

import matplotlib
matplotlib.use("Agg")


@pytest.fixture(scope="module")
def trained():
    from kohonen_europe import load_data, run, build_assignments
    with open("configs/kohonen_europe.json") as f:
        cfg = json.load(f)
    cfg["epochs"] = 10
    countries, X = load_data(cfg["data"])
    som, coords = run(cfg, X)
    assignments = build_assignments(countries, coords)
    return cfg, countries, X, som, coords, assignments


# --- country_map ---

def test_country_map_creates_file(trained):
    from kohonen_europe import plot_country_map
    cfg, countries, _, _, coords, assignments = trained
    with tempfile.TemporaryDirectory() as d:
        path = os.path.join(d, "country_map.png")
        plot_country_map(assignments, cfg["grid_rows"], cfg["grid_cols"], path)
        assert os.path.exists(path)


def test_country_map_nonempty(trained):
    from kohonen_europe import plot_country_map
    cfg, countries, _, _, coords, assignments = trained
    with tempfile.TemporaryDirectory() as d:
        path = os.path.join(d, "country_map.png")
        plot_country_map(assignments, cfg["grid_rows"], cfg["grid_cols"], path)
        assert os.path.getsize(path) > 0


# --- u_matrix ---

def test_u_matrix_plot_creates_file(trained):
    from kohonen_europe import plot_u_matrix
    cfg, _, _, som, _, _ = trained
    with tempfile.TemporaryDirectory() as d:
        path = os.path.join(d, "u_matrix.png")
        plot_u_matrix(som, path)
        assert os.path.exists(path)


def test_u_matrix_plot_nonempty(trained):
    from kohonen_europe import plot_u_matrix
    cfg, _, _, som, _, _ = trained
    with tempfile.TemporaryDirectory() as d:
        path = os.path.join(d, "u_matrix.png")
        plot_u_matrix(som, path)
        assert os.path.getsize(path) > 0


# --- hit_map ---

def test_hit_map_creates_file(trained):
    from kohonen_europe import plot_hit_map
    cfg, countries, _, _, coords, assignments = trained
    with tempfile.TemporaryDirectory() as d:
        path = os.path.join(d, "hit_map.png")
        plot_hit_map(assignments, cfg["grid_rows"], cfg["grid_cols"], len(countries), path)
        assert os.path.exists(path)


def test_hit_map_nonempty(trained):
    from kohonen_europe import plot_hit_map
    cfg, countries, _, _, coords, assignments = trained
    with tempfile.TemporaryDirectory() as d:
        path = os.path.join(d, "hit_map.png")
        plot_hit_map(assignments, cfg["grid_rows"], cfg["grid_cols"], len(countries), path)
        assert os.path.getsize(path) > 0


def test_hit_map_counts_sum_to_n_countries(trained):
    cfg, countries, _, _, coords, assignments = trained
    total = sum(len(v) for v in assignments.values())
    assert total == len(countries)


# --- all three plots generated by main script ---

def test_main_generates_all_plots(tmp_path):
    import subprocess, sys
    with open("configs/kohonen_europe.json") as f:
        cfg = json.load(f)
    cfg["epochs"] = 10
    cfg["output_dir"] = str(tmp_path)
    tmp_cfg = tmp_path / "test_cfg.json"
    tmp_cfg.write_text(json.dumps(cfg))

    result = subprocess.run(
        [sys.executable, "kohonen_europe.py", "--config", str(tmp_cfg)],
        capture_output=True, text=True,
    )
    assert result.returncode == 0, result.stderr
    assert (tmp_path / "country_map.png").exists()
    assert (tmp_path / "u_matrix.png").exists()
    assert (tmp_path / "hit_map.png").exists()
